#pragma once

#define AUTOGEN_DIR_PATH "\\..\\..\\Sources\\Core\\autogen"

#define SHADER_STRUCT_FILE_NAME "ssfn.h"

#define SHADER_BINDINGS_FILE_NAME "sbfn.h"

#define AUTOGEN_HEADER_WARNING "//! AUTOGENERATED ! DO NOT MODIFY THIS FILE !!!"

#define beginBrace std::string("\n{")

#define endBrace std::string("\n}")

#define beginNAMESPACE(name) std::string("namespace ") + std::string(name) + beginBrace

#define BINDINGS_DECL "std::vector<vk::DescriptorSetLayoutBinding> " + beginBrace

